codecov:
  require_ci_to_pass: yes
  token: 82c6532f-8a30-4012-900b-0fcbeac2661e
coverage:
  ignore:
    - "Examples"
    - "Tests"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no]
