name: run all test
on: 
  push
jobs:
  run-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate xcode project
        run: swift package generate-xcodeproj
      - name: Generate xcode test report
        run: xcodebuild clean test -scheme SwiftDataStructure-Package -destination platform="macOS" -enableCodeCoverage YES  -derivedDataPath ./derivedData
      - name: Generate coverage report
        run: bash <(curl -s https://codecov.io/bash) -J '^SwiftDataStructure$' -D ./derivedData -c -X gcov
