name: run all test
on: 
  push
jobs:
  run-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate xcode project
        run: swift package generate-xcodeproj -enableCodeCoverage
      - name: Generate xcode test report
        run: xcodebuild -scheme SwiftDataStructure-Package clean test
      - name: Generate coverage report
        run: bash <(curl -s https://codecov.io/bash)
